### ISSUE TITLE
Food outside wall / Transitions / Green Splitting Blobs 

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#131] opened 2015-06-02 17:07 UTC
So as the title states, there's a few things' I'd like to discuss.

1.) First of all, I've noticed food spawning outside the wall. This is a minor issue and could possibly be fixed relatively quickly.

2.) Transitioning. I've noticed when you eat the "food" the transition between your current size and the next size is instantaneous. Could you add the transition of the "expansion" from your current size to the new size? If you play the original game and eat some food, you'll know what I mean.

3.) This is more of a feature request, but could you add the "green blobs" (like in the original game) that when you fly into them, you split? They need to be randomly placed in a static position - at least that's how I think they're placed.

4.) Finally, could you increase the size of the food so it's bigger? I think double the size might do - just so it's more like the original game thus more of a clone :)

Thanks!

**Comment by IgorAntun** [comment] 2015-06-02 17:21
**1)** How old is your clone? This food bug should've been fixed at #86 - *(Duplicate of issue #76)*.

**2)** Great idea!

**3)** Those are viruses. *(Duplicate of issue #25)*

**4)** Good point.

Could you please make separate issues for **2** and **4**?

**Closed by IgorAntun** 2015-06-02 17:21 UTC
Labels: duplicate, enhancement

**Comment by Crasha** [comment] 2015-06-02 17:27
Hi,

Thanks for your reply. I've literally just cloned the master repo before, and ran "git remote update" in the directory.

Sure, I'll make separate issues shortly.
