### ISSUE TITLE
Merging makes you smaller & slower.

### ISSUE THREAD

**Issue by higoing00** [huytd/agar.io-clone#328] opened 2015-10-06 17:17 UTC
This is a bug. 100%

I had 100 mass on me, and I had split up 4 times. 10 seconds later, i start merging and instead of getting bigger, I merged into my smallest piece which was 17. Every time you split, it forces you to shrink to the smallest piece.

Lastly, smaller means you should be faster. I also noticed when you split, you are as slow as if you had over 900 mass.

Plz fix. D:

**Comment by abalabahaha** [comment] 2015-10-06 18:33
Duplicate of #326 , appending slowness to that issue

**Closed by abalabahaha** 2015-10-06 18:33 UTC
