### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by herohamp** [huytd/agar.io-clone#494] opened 2017-04-22 22:02 UTC
root@hampton:/var/www/agario# gulp run
[18:01:40] Using gulpfile /var/www/agario/gulpfile.js
[18:01:40] Starting 'lint'...
[18:01:40] Starting 'move-client'...
[18:01:41] Finished 'lint' after 894 ms
[18:01:41] Starting 'build-server'...
[18:01:41] Starting 'test'...
[18:01:41] Finished 'test' after 1.74 ms
[18:01:41] Starting 'todo'...
[18:01:41] Finished 'todo' after 1.74 ms

  util.js
    #massToRadius
      ✓ should return non-zero radius on zero input
      ✓ should convert masses to a circle radius
    #validNick
      ✓ should allow empty player nicknames
      ✓ should allow ascii character nicknames
      ✓ should disallow unicode-dependent alphabets
      ✓ should disallow spaces in nicknames
    #log
      1) should compute the log_{base} of a number
    #getDistance
      ✓ should return a positive number

  7 passing (13ms)
  1 failing

  1) util.js #log should compute the log_{base} of a number:

      AssertionError: expected 2.0000000000000004 to deeply equal 2
      + expected - actual

      -2.0000000000000004
      +2
      
      at Context.<anonymous> (test/util.js:86:31)

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: 1 test failed.

**Comment by abalabahaha** [comment] 2017-04-22 22:10
Duplicate of #478

**Closed** 2017-04-22 22:10 UTC
Labels: duplicate
