### ISSUE TITLE
Nickname limitation issue: Spacebar.

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#144] opened 2015-06-03 02:12 UTC
Hello Dear Developers

Where I will make some nickname with spacerbar i mean example: nick tester it doesn't allow me to join on the server and even server didin't notice me the nickname can not be with spacebar etc.

Best Regards
Mateusz

**Comment by IgorAntun** [comment] 2015-06-03 02:19
You should be able to use a blank name, but you can't use a 'space'. It should show a red alert. It's working just fine here, though.
Maybe try updating your clone :)

**Comment by hunterpl** [comment] 2015-06-03 02:32
try on this followed link:
http://agar.ts3bahu.com:3000 i typed: " nick test " not warnings etc.

**Comment by IgorAntun** [comment] 2015-06-03 02:34
That server is probably outdated.

**Comment by hunterpl** [comment] 2015-06-03 02:41
Downloaded ZIP file from: https://github.com/huytd/agar.io-clone updated server 2 minutes ago and I don't know but when I connect to the server the speed is much higher than normal.

**Comment by IgorAntun** [comment] 2015-06-03 02:51
I updated the speed so it looks more like the original agar.io.

**Comment by hunterpl** [comment] 2015-06-03 03:00
On the beginning it's look like much more speed than agar.io standard maybe set it a little bit less what do you think?

**Comment by IgorAntun** [comment] 2015-06-03 03:01
It looks like it's too fast because there isn't as much food as there's on agar yet, and also there's not as many players. But as far as I tested, it's pretty close to agar's speed.

**Comment by hunterpl** [comment] 2015-06-03 03:05
Where can I change the size zone? Is it possible to change this?

**Comment by IgorAntun** [comment] 2015-06-03 03:06
What size zone? I think we should move this conversation to our [Gitter](https://gitter.im/huytd/agar.io-clone?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to avoid cluttering this Issue.

**Comment by IgorAntun** [comment] 2015-06-03 03:06
Also gonna close this since it's not a bug in the current code.

**Closed** 2015-06-03 03:07 UTC
Labels: bug, won't fix
