### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Husnain1** [huytd/agar.io-clone#333] opened 2015-10-12 11:49 UTC
Please add skins and virus.

**Comment by abalabahaha** [comment] 2015-10-12 17:22
Duplicate of #25, #50

**Closed by abalabahaha** 2015-10-12 17:22 UTC

**Comment by 3642066** [comment] 2016-01-23 07:41
I can help getting Facebook profile picture with Facebook login, if you will implement skins, please teach me what you need, so i fork and implement the Facebook Login passing the profile picture as you need, maybe, of course, if you like the idea, i just need a method to set a custom skin .
