### ISSUE TITLE
Invisible Players & out-of-sync player counter

### ISSUE THREAD

**Issue by ZeHaxor** [huytd/agar.io-clone#88] opened 2015-06-01 02:56 UTC
Seeming randomly, after playing with 15 people, the largest person went invisible, you could clearly see him eating the food particles as he approached, then you get disconnected as he reached you.
Also, once somebody has died, the player counter loses count somehow, showing 13 when 15 players were clearly visible.

I'm investigating these now.

**Comment by huytd** [comment] 2015-06-01 07:24
Confirmed. I got this error sometimes. still have no idea. 
It should be a problem with the user array handling, with some dupplicate when adding and removing users.

**Comment by IgorAntun** [comment] 2015-06-26 21:01
I think this has been fixed?

**Comment by IgorAntun** [comment] 2015-07-07 01:58
Closing this since there hasn't been any activity. If this is still happening, please re-open it.

**Closed by IgorAntun** 2015-07-07 01:58 UTC
Labels: bug, help wanted
