### ISSUE TITLE
Cell doesn't disappear when eaten - Also Restart

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#208] opened 2015-06-14 13:01 UTC
1.) I opened two tabs up to trial the PVP out, and I noticed that when my smaller cell came in contact with the big cell which was in another tab, it didn't do anything, and I was free to move over the top of the other cell which should have "eaten" the smaller cell. However, when I opened my first tab up with the big cell, the smaller cell got eaten.

2.) When you get "eaten" the menu box should transition back in via fading or sliding into the centre of the screen. With this in mind, the actual game play should be happening in the background, without entering the game thus you're in some kind of spectator mode. If you open agar.io, you'll see what I mean.

**Comment by Buskcoin** [comment] 2015-06-14 17:34
I too was confused by your first issue but...
> Gameplay Rules

> Players who haven't eaten yet cannot be eaten

**Comment by IgorAntun** [comment] 2015-06-14 22:14
Yeah, as @Buskcoin pointed, this is how it should be. Players who haven't yet eaten, can't be eaten.
Also 2) is a somewhat duplicate of #134 and possibly a new issue (enhacement).

**Closed by IgorAntun** 2015-06-14 22:14 UTC
Labels: won't fix
