### ISSUE TITLE
Add leaderboard

### ISSUE THREAD

**Issue by siddharthlohchab** [huytd/agar.io-clone#259] opened 2015-07-08 08:02 UTC
It is missing the most important thing a LEADERBOARD.
I hope someone will work upon it!

**Comment by ama291** [comment] 2015-07-08 18:15
It has a leaderboard, the most recent demo is online at: http://agar.ts3bahu.com:3000/ and on the top right, the players are ranked in order.

**Comment by IgorAntun** [comment] 2015-07-08 21:34
Yeah this is a duplicate of #119, which was implemented and closed with #221 :)

**Closed by IgorAntun** 2015-07-08 21:34 UTC
Labels: duplicate

**Comment by siddharthlohchab** [comment] 2015-07-09 07:42
Thanks!!
