### ISSUE TITLE
Crash server every time.

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#151] opened 2015-06-03 11:14 UTC
Hello Dear Developers

I have crash server every time but in different time intervals, always see " Cannot read property 'name' of null "

crash log:
TypeError: Cannot read property 'name' of null
    at Socket.<anonymous> (/var/www/agar/server/server.js:166:44)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/var/www/agar/node_modules/socket.io/lib/socket.js:129:10)
    at Socket.onclose (/var/www/agar/node_modules/socket.io/lib/socket.js:418:8)
    at Client.onclose (/var/www/agar/node_modules/socket.io/lib/client.js:230:12)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/var/www/agar/node_modules/socket.io/node_modules/engine.io/lib/socket.js:248:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.emit (events.js:92:17)
    at WebSocket.Transport.onClose (/var/www/agar/node_modules/socket.io/node_modules/engine.io/lib/transport.js:113:8)
root@ts3bahu:/var/www/agar# node server/server.js

**Comment by themuddfamily2** [comment] 2015-06-03 11:18
I have reported this already in the gitter chat, it happens when a user is removed from the array and is DC'd before the message saying he died appears in chat.

**Comment by artuross** [comment] 2015-06-03 11:21
I've seen this, but can't figure out how is it that player who want to disconnect is not in the users' array.

https://github.com/huytd/agar.io-clone/blob/master/server/server.js#L166

Function `findPlayer` returns either user object or `null`. And then we try to access `null.name` (which is obviously an error).

**Comment by themuddfamily2** [comment] 2015-06-03 11:22
Possibly a check if the player is null then no message is sent in chat or something?

**Comment by artuross** [comment] 2015-06-03 11:23
@themuddfamily2 But a player shouldn't be removed from that array until that very moment.

**Comment by themuddfamily2** [comment] 2015-06-03 11:38
The easiest way to solve this would be a check on if the player ID exists in the array and skip the rest of the steps if it doesn't?

**Comment by IgorAntun** [comment] 2015-06-03 14:46
Duplicate of #139

**Closed by IgorAntun** 2015-06-03 14:46 UTC
Labels: duplicate
