### ISSUE TITLE
nodemon crashing while reading config.json

### ISSUE THREAD

**Issue by vikramdurai** [huytd/agar.io-clone#495] opened 2017-04-25 05:15 UTC
^
My config file is as follows:
```
{
    "host": "0.0.0.0",
    "port": 3000,
    "logpath": "logger.php",
    "foodMass": 1,
    "fireFood": 20,
    "limitSplit": 16,
    "defaultPlayerMass": 10,
  	"virus": {
      "fill": "#33ff33",
    	"stroke": "#19D119",
  		"strokeWidth": 20,
  		"defaultMass": {
              "from": 100,
              "to": 150
          },
  		"splitMass": 180
  	},
    "gameWidth": 5000,
    "gameHeight": 5000,
    "adminPass": "DEFAULT",
    "gameMass": 20000,
    "maxFood": 1000,
    "maxVirus": 50,
    "slowBase": 4.5,
    "logChat": 0,
    "networkUpdateFactor": 40,
    "maxHeartbeatInterval": 5000,
    "foodUniformDisposition": true,
    "virusUniformDisposition": false,
    "newPlayerInitialPosition": "farthest",
    "massLossRate": 1,
    "minMassLoss": 50,
    "mergeTimer": 15,
    "sqlinfo":{
      "connectionLimit": 100,
      "host": "localhost",
      "user": "root",
      "password": "DEFAULT",
      "database": "DEFAULT",
      "debug": false
    }
}

```
I'm getting this weird error:
```
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
    --------------------
    at Protocol._enqueue (C:\Users\vikas\agar.io-clone\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (C:\Users\vikas\agar.io-clone\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (C:\Users\vikas\agar.io-clone\node_modules\mysql\lib\Connection.js:130:18)
    at Object.<anonymous> (C:\Users\vikas\agar.io-clone\bin\server\server.js:44:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }
```

**Comment by abalabahaha** [comment] 2017-04-25 10:10
Duplicate of #488

**Closed by abalabahaha** 2017-04-25 10:10 UTC
